import { PhonemeGuide } from '@/types'

export const phonemeGuides: PhonemeGuide[] = [
  {
    id: 'th',
    phoneme: 'Th',
    name: 'TH Sound',
    category: 'Fricatives',
    difficulty: 'medium',
    description: 'The "th" sound is made by placing your tongue between your teeth.',
    tonguePosition: 'Tip of tongue between upper and lower front teeth',
    lipPosition: 'Slightly parted, relaxed',
    airflow: 'Continuous airflow over the tongue',
    examples: ['think', 'that', 'through', 'breathe', 'weather'],
    tips: [
      'Place your tongue tip gently between your teeth',
      'Let air flow over your tongue without stopping',
      'Practice slowly, feeling the vibration',
      'The voiced "th" (as in "that") vibrates your throat',
    ],
    commonMistakes: ['Substituting with "f" or "v"', 'Not placing tongue between teeth'],
  },
  {
    id: 'r',
    phoneme: 'R',
    name: 'R Sound',
    category: 'Liquids',
    difficulty: 'hard',
    description: 'The "r" sound involves curling the tongue slightly without touching the roof of the mouth.',
    tonguePosition: 'Tongue curled back, tip raised toward roof of mouth but not touching',
    lipPosition: 'Slightly rounded',
    airflow: 'Continuous, voiced',
    examples: ['red', 'run', 'car', 'around', 'very'],
    tips: [
      'Curl your tongue tip slightly backward',
      'Keep your tongue sides touching your upper molars',
      'Do not touch the roof of your mouth with your tongue tip',
      'Practice growling like a tiger to feel the position',
    ],
    commonMistakes: ['Substituting with "w"', 'Tongue touching roof of mouth'],
  },
  {
    id: 's',
    phoneme: 'S',
    name: 'S Sound',
    category: 'Fricatives',
    difficulty: 'easy',
    description: 'The "s" sound is a hissing sound made by directing air over the tongue.',
    tonguePosition: 'Tongue tip behind upper front teeth, slight groove in center',
    lipPosition: 'Slightly spread in a small smile',
    airflow: 'Strong, continuous airstream',
    examples: ['sun', 'see', 'miss', 'house', 'stress'],
    tips: [
      'Keep your tongue tip just behind your top teeth',
      'Create a narrow channel for air to flow',
      'The sound should be a clear hiss',
      'Practice making a snake sound',
    ],
    commonMistakes: ['Lisping (air escaping over sides)', 'Tongue between teeth'],
  },
  {
    id: 'l',
    phoneme: 'L',
    name: 'L Sound',
    category: 'Liquids',
    difficulty: 'medium',
    description: 'The "l" sound is made by touching your tongue to the roof of your mouth.',
    tonguePosition: 'Tongue tip touches the ridge behind upper front teeth',
    lipPosition: 'Relaxed, slightly open',
    airflow: 'Air flows over sides of tongue',
    examples: ['love', 'light', 'bell', 'full', 'lily'],
    tips: [
      'Press tongue tip firmly against the ridge behind your top teeth',
      'Let air flow around the sides of your tongue',
      'Keep the back of your tongue down',
      'Practice moving between "la" and "al" sounds',
    ],
    commonMistakes: ['Substituting with "w" or "y"', 'Tongue too far back'],
  },
  {
    id: 'ch',
    phoneme: 'Ch',
    name: 'CH Sound',
    category: 'Affricates',
    difficulty: 'medium',
    description: 'The "ch" sound combines a stop and a fricative in quick succession.',
    tonguePosition: 'Tongue tip touches ridge behind teeth, then releases',
    lipPosition: 'Rounded and pushed forward slightly',
    airflow: 'Burst of air followed by friction',
    examples: ['chair', 'church', 'match', 'teacher', 'child'],
    tips: [
      'Start with your tongue pressed against the roof of your mouth',
      'Release with a rush of air like a sneeze',
      'Round your lips slightly',
      'Think of it as "t" + "sh" blended together',
    ],
    commonMistakes: ['Making only "sh" sound', 'Not enough initial stop'],
  },
  {
    id: 'sh',
    phoneme: 'Sh',
    name: 'SH Sound',
    category: 'Fricatives',
    difficulty: 'easy',
    description: 'The "sh" sound is a hushing sound made with rounded lips.',
    tonguePosition: 'Tongue raised and pulled back, not touching roof',
    lipPosition: 'Rounded and pushed forward',
    airflow: 'Continuous airstream through center of mouth',
    examples: ['she', 'ship', 'wish', 'brush', 'ocean'],
    tips: [
      'Round your lips like you\'re going to whistle',
      'Raise the front of your tongue toward the roof of your mouth',
      'Create a "shushing" sound like quieting a baby',
      'Practice in front of a mirror to see lip position',
    ],
    commonMistakes: ['Making "s" instead', 'Lips not rounded enough'],
  },
  {
    id: 'k',
    phoneme: 'K',
    name: 'K Sound',
    category: 'Stops',
    difficulty: 'easy',
    description: 'The "k" sound is a stop consonant made by blocking airflow at the back of the mouth.',
    tonguePosition: 'Back of tongue pressed against soft palate',
    lipPosition: 'Relaxed, neutral',
    airflow: 'Complete blockage followed by sudden release',
    examples: ['cat', 'kite', 'back', 'school', 'quick'],
    tips: [
      'Press the back of your tongue against the soft part of your palate',
      'Build up air pressure, then release suddenly',
      'Feel the "pop" of air when you release',
      'Practice with "k-k-k" repetitions',
    ],
    commonMistakes: ['Making the sound too far forward in mouth', 'Insufficient air pressure'],
  },
  {
    id: 'g',
    phoneme: 'G',
    name: 'G Sound',
    category: 'Stops',
    difficulty: 'easy',
    description: 'The "g" sound is a voiced stop consonant similar to "k" but with vocal cord vibration.',
    tonguePosition: 'Back of tongue pressed against soft palate',
    lipPosition: 'Relaxed, neutral',
    airflow: 'Complete blockage with vocal cord vibration, then release',
    examples: ['go', 'big', 'dog', 'again', 'tiger'],
    tips: [
      'Same tongue position as "k" but add voice',
      'Feel your throat vibrate when you make the sound',
      'Practice alternating between "k" and "g" to feel the difference',
      'Place your hand on your throat to feel vibration',
    ],
    commonMistakes: ['Making voiceless "k" instead', 'Weak vocal cord engagement'],
  },
  {
    id: 'p',
    phoneme: 'P',
    name: 'P Sound',
    category: 'Stops',
    difficulty: 'easy',
    description: 'The "p" sound is made by pressing your lips together and releasing a burst of air.',
    tonguePosition: 'Relaxed, neutral',
    lipPosition: 'Lips pressed firmly together',
    airflow: 'Complete blockage at lips, then sudden release',
    examples: ['put', 'apple', 'cup', 'happy', 'stop'],
    tips: [
      'Press your lips firmly together',
      'Build up air pressure behind your lips',
      'Release suddenly with a "pop"',
      'Practice holding your lips closed for a moment before releasing',
    ],
    commonMistakes: ['Insufficient lip closure', 'Adding extra vowel sound after'],
  },
  {
    id: 'b',
    phoneme: 'B',
    name: 'B Sound',
    category: 'Stops',
    difficulty: 'easy',
    description: 'The "b" sound is a voiced version of "p" with vocal cord vibration.',
    tonguePosition: 'Relaxed, neutral',
    lipPosition: 'Lips pressed firmly together',
    airflow: 'Complete blockage at lips with vocal cord vibration, then release',
    examples: ['ball', 'big', 'cab', 'table', 'robber'],
    tips: [
      'Same lip position as "p" but add voice',
      'Feel your lips vibrate when making the sound',
      'Practice feeling the difference between "p" and "b"',
      'Your vocal cords should vibrate throughout',
    ],
    commonMistakes: ['Making voiceless "p" instead', 'Weak voice onset'],
  },
  {
    id: 'f',
    phoneme: 'F',
    name: 'F Sound',
    category: 'Fricatives',
    difficulty: 'easy',
    description: 'The "f" sound is made by placing your upper teeth on your lower lip.',
    tonguePosition: 'Relaxed, away from teeth',
    lipPosition: 'Upper teeth touching lower lip lightly',
    airflow: 'Continuous airstream between teeth and lip',
    examples: ['fun', 'after', 'leaf', 'photo', 'coffee'],
    tips: [
      'Gently bite your lower lip with your upper teeth',
      'Let air flow continuously between your teeth and lip',
      'The sound should be a soft friction',
      'Don\'t bite too hard - just light contact',
    ],
    commonMistakes: ['Substituting with "th"', 'Too much lip pressure'],
  },
  {
    id: 'v',
    phoneme: 'V',
    name: 'V Sound',
    category: 'Fricatives',
    difficulty: 'easy',
    description: 'The "v" sound is a voiced version of "f" with vocal cord vibration.',
    tonguePosition: 'Relaxed, away from teeth',
    lipPosition: 'Upper teeth touching lower lip lightly',
    airflow: 'Continuous airstream with vocal cord vibration',
    examples: ['very', 'love', 'five', 'have', 'never'],
    tips: [
      'Same position as "f" but add voice',
      'Feel your throat and lips vibrate',
      'Practice feeling the difference between "f" and "v"',
      'Place your hand on your throat to feel vibration',
    ],
    commonMistakes: ['Making voiceless "f" instead', 'Weak vocal cord engagement'],
  },
]

export function getPhonemeById(id: string): PhonemeGuide | undefined {
  return phonemeGuides.find((guide) => guide.id === id)
}

export function getPhonemesByCategory(category: PhonemeGuide['category']): PhonemeGuide[] {
  return phonemeGuides.filter((guide) => guide.category === category)
}

export function getPhonemesByDifficulty(difficulty: PhonemeGuide['difficulty']): PhonemeGuide[] {
  return phonemeGuides.filter((guide) => guide.difficulty === difficulty)
}
